### ISSUE TITLE
Include state parameter in redirects with errors

### ISSUE THREAD

**Issue by arscan** [smart-on-fhir/smart-launcher#13]
According to [4.1.2.1.  Error Response](https://tools.ietf.org/html/rfc6749#section-4.1.2.1) in the OAuth2.0 RFC, redirects with errors have two required querystring params: `error`, and `state` (if `state` is provided by the client).  This does not appear to pass `state` to the client redirect URI when an error occurs.

This is important for apps that use `state` as a reference to determine session information.  This came up in https://github.com/siteadmin/inferno/issues/155, as Inferno as a client uses `state` in this way.

**Comment by vlad-ignatov** [comment]
Thank you for reporting this. It should be fixed now. Here is an example (just click the "Launch App" button): https://launch.smarthealthit.org/?auth_error=auth_invalid_client_id&fhir_version_1=r4&fhir_version_2=r4&iss=&launch_ehr=1&launch_url=https%3A%2F%2Fexamples.smarthealthit.org%2Fgrowth-chart-app%2Flaunch.html&patient=17ff80a3-dda8-4a58-a8c5-6fe94ad0d747&prov_skip_auth=1&provider=&pt_skip_auth=1&public_key=&sb=&sde=&sim_ehr=0&token_lifetime=15&user_pt=
