### ISSUE TITLE
nonce not reflected in id_token when provided in the authentication request

### ISSUE THREAD

**Issue by dteirney** [smart-on-fhir/smart-launcher#18]
If a `nonce` is provided in the authentication request it needs to be reflected back in the `id_token` as per https://openid.net/specs/openid-connect-core-1_0.html#IDToken.

I ran into this when testing integration via our 3rd party OIDC Relying Party implementation when it was not validating the received `id_token`.

**Comment by vlad-ignatov** [comment]
Thanks David,

The launcher does not exactly include or support OIDC. However, I do agree that it makes sense to partially support the openid spec, just to improve the apps integration as much as possible.

I am currently on vacation, traveling a lot and I don't always WiFy access so I might not be able to react very quickly - I hope it is not urgent. I will try to digest what you've done soon and merge it if possible.
