### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by radamisa** [smart-on-fhir/smart-launcher#27]
Hi,

It appears the certificate has expired for https://r2.smarthealthit.org/ and https://r3.smarthealthit.org/

**Comment by jwnewman12** [comment]
It looks like this is a recurrence, https://github.com/smart-on-fhir/smart-launcher/issues/24
paging  @vlad-ignatov  ... maybe he can fix it

**Comment by vlad-ignatov** [comment]
Thanks for notifying! It should be fixed now.
