### ISSUE TITLE
Binary Resources

### ISSUE THREAD

**Issue by gotdan** [smart-on-fhir/smart-launcher#3]
via SMART discussion group:

Sending Binary with pdf, png, or jpg - Posted content Base64 is different and incorrect when read back from Launch FHIR Server.

When I use the same code hitting the Hapi FHIR public Test server, it works correctly.

Is Binary not supposed to support POST/PUT on that server?

**Comment by vlad-ignatov** [comment]
Actually, this was about reading the already inserted binary resources. Our proxy was messing them up, assuming that everything is a JSON... Should be fixed now. Example: https://launch.smarthealthit.org/v/r3/fhir//Binary/smart-2-document
