### ISSUE TITLE
Auth Server at launch.smarthealthit.org/v/r2/auth/token Does Not Appear To Meet OAuth2.0 Spec

### ISSUE THREAD

**Issue by joedimarzio** [smart-on-fhir/smart-launcher#32]
We are following the auth flow in the specs found [here](http://hl7.org/fhir/smart-app-launch/#smart-authorization-and-resource-retrieval) and I have found that multiple requests can be sent to the auth server [token endpoint](http://hl7.org/fhir/smart-app-launch/#smart-authorization-and-resource-retrieval) with the same code/state and an access token will still be granted each time. This is a security weakness and does not meet OAuth spec. I realize this is a test server but figured it is best to raise awareness.

**Comment by vlad-ignatov** [comment]
That is correct. This is a mock server for testing purposes. People use it to test their SMART apps during development. It is not a real authentication server (does not even require registration) and as such, it will never really be secure.
