### ISSUE TITLE
Auth Server at https://launch.smarthealthit.org/v/r4/fhir does not validate existence of redirect_uri

### ISSUE THREAD

**Issue by SaschaZeGerman** [smart-on-fhir/smart-launcher#43]
When sending an authorization request that includes a 'redirect_uri' the /token endpoint should fail the code exchange request if the same redirect_uri was not included.

The last paragraph in this section explains it:
https://tools.ietf.org/html/rfc6749#section-4.1.3

Even though this is a test server, if developers use this to verify their implementation their code potentially fails in a real system.

**Comment by vlad-ignatov** [comment]
This should be fixed now
