### ISSUE TITLE
Calling https://launch.smarthealthit.org/.well-known/openid-configuration/ gives Cannot GET /auth/authorize

### ISSUE THREAD

**Issue by HungUnicorn** [smart-on-fhir/smart-launcher#48]
When calling
https://launch.smarthealthit.org/.well-known/openid-configuration/

Gives Cannot GET /auth/authorize 

, is it because the payload has extra "/"?

https://launch.smarthealthit.org/.well-known/openid-configuration/

returns
```
authorization_endpoint: "https://launch.smarthealthit.org/.well-known/openid-configuration//auth/authorize",
token_endpoint: "https://launch.smarthealthit.org/.well-known/openid-configuration//auth/token",
introspection_endpoint: "https://launch.smarthealthit.org/.well-known/openid-configuration//auth/introspect",
```

**Comment by vlad-ignatov** [comment]
Thank you for reporting this. I can see the double slash issue and I am working on it, but before I commit anything I want to be sure I understand you. What do you mean by "When calling https://launch.smarthealthit.org/.well-known/openid-configuration/ Gives Cannot GET /auth/authorize"? Who calls it and who is "giving" that result? 

Loading https://launch.smarthealthit.org/.well-known/openid-configuration//auth/authorize in the browser returns "Cannot GET /.well-known/openid-configuration//auth/authorize", which is a little different.

**Comment by HungUnicorn** [comment]
it's my http request that is used for discovery. Would be glad to see if this is fixed

**Comment by vlad-ignatov** [comment]
This should be fixed now. Be aware that the well-known locations have changed to
https://launch.smarthealthit.org/v/r2/fhir/.well-known/openid-configuration
https://launch.smarthealthit.org/v/r3/fhir/.well-known/openid-configuration
https://launch.smarthealthit.org/v/r4/fhir/.well-known/openid-configuration
https://launch.smarthealthit.org/v/r2/fhir/.well-known/smart-configuration
https://launch.smarthealthit.org/v/r3/fhir/.well-known/smart-configuration
https://launch.smarthealthit.org/v/r4/fhir/.well-known/smart-configuration

**Comment by HungUnicorn** [comment]
Hi @vlad-ignatov  what's the difference between openid-configuration and smart-configuration? I know the previous one is for OpenId Connect discovery, so what's smart-configuration for?

**Comment by HungUnicorn** [comment]
Found it in the FHIR doc https://build.fhir.org/ig/Healthedata1/smart-app-launch-brver/conformance/index.html#using-well-known. so it's an extension of openid-configuration
