### ISSUE TITLE
Support CDS Hooks appContext for SMART app launches

### ISSUE THREAD

**Issue by kpshek** [smart-on-fhir/smart-launcher#5]
CDS Hooks defines the notion of an 'appContext' field which allows a CDS Service to share data between a SMART app link in a CDS card and their SMART app. Effectively, the SMART app link in a CDS card contains `appContext` and the EHR passes this value back alongside the access token when the SMART app launches.

See [this thread on the CDS Hooks mailing list](https://groups.google.com/d/msg/cds-hooks/NsSkpNhN0-w/uppoQQgqAgAJ) for additional history/context.

See also https://cds-hooks.org/specification/1.0/#link

> An optional field that allows the CDS Service to share information from the CDS card with a subsequently launched SMART app. The appContext field should only be valued if the link type is smart and is not valid for absolute links. The appContext field and value will be sent to the SMART app as part of the OAuth 2.0 access token response, alongside the other SMART launch parameters when the SMART app is launched. Note that appContext could be escaped JSON, base64 encoded XML, or even a simple string, so long as the SMART app can recognize it.

**Comment by jmandel** [comment]
Fixed by #17
