### ISSUE TITLE
IdToken Issuer does not provide correct Fhir Version url

### ISSUE THREAD

**Issue by jstone-krames** [smart-on-fhir/smart-launcher#54]
The IdToken provided in the access token result JWT contains an invalid issuer and should contain the fhir version.

This results in the in ability to construct a proper Uri using the iss claim as the base url to retrieve the open id configuration.

Issuer comes in as https://launch.smarthealthit.org/
but should be https://launch.smarthealthit.org/v/r{x}

**Comment by vlad-ignatov** [comment]
I think this should be fixed now. FYI, the well-known locations have changed again to https://launch.smarthealthit.org/v/r{x}/fhir/.well-known/xxx
Let me know if that works for you.

**Comment by jstone-krames** [comment]
All seems good to go!  Thank you much.
